import { type NextPage } from "next";
import Head from "next/head";
import { Fragment } from "react";
import { Disclosure, Menu, Transition } from "@headlessui/react";
import { Bars3Icon, BellIcon, XMarkIcon } from "@heroicons/react/24/outline";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "~/utils/api";

const navigation = [
  { name: "About", href: "#", current: true },

  { name: "Projects", href: "#", current: false },
];

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Tiaan broodryk</title>
        <meta name="description" content="Generated by Tiaan Broodryk" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Disclosure as="nav" className="bg-gray-800">
        {({ open }) => (
          <>
            <div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
              <div className="relative flex h-16 items-center justify-between">
                <div className="absolute inset-y-0 left-0 flex items-center sm:hidden">
                  {/* Mobile menu button*/}
                  <Disclosure.Button className="inline-flex items-center justify-center rounded-md p-2 text-gray-700 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">
                    <span className="sr-only">Open main menu</span>
                    {open ? (
                      <XMarkIcon className="block h-6 w-6" aria-hidden="true" />
                    ) : (
                      <Bars3Icon className="block h-6 w-6" aria-hidden="true" />
                    )}
                  </Disclosure.Button>
                </div>
                <div className="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
                  <div className="flex flex-shrink-0 items-center">
                    <Image
                      src="/assets/images/profile.jpg"
                      width={800 * 4}
                      height={600 * 4}
                      alt={""}
                      className="block h-8 w-auto rounded-full border-2 border-white lg:hidden"
                    />

                    <Image
                      src="/assets/images/profile.jpg"
                      width={800 * 4}
                      height={600 * 4}
                      alt={""}
                      className="hidden h-8 w-auto rounded-full border-2 border-white lg:block"
                    />
                  </div>
                  <div className="hidden sm:ml-6 sm:block">
                    <div className="flex space-x-4">
                      <a></a>
                    </div>
                  </div>
                </div>
                <div className="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
                  {/* Profile dropdown */}
                </div>
              </div>
            </div>

            <Disclosure.Panel className="sm:hidden">
              <div className="space-y-1 px-2 pb-3 pt-2">
                <Disclosure.Button></Disclosure.Button>
              </div>
            </Disclosure.Panel>
          </>
        )}
      </Disclosure>
      <div className="h-full min-h-screen bg-gray-100">
        <div className="mx-auto h-full max-w-7xl sm:px-6 lg:px-8">
          {/* We've used 3xl here, but feel free to try other max-widths based on your needs */}
          <div className="mx-auto max-w-6xl">
            <div className="bg-white p-5 pt-10">
              <div className="rounded-xl bg-gray-50 pb-5 shadow-xl xl:p-5">
                <div className="mx-auto flex max-w-7xl flex-col items-center gap-x-8 gap-y-24 px-6  sm:gap-y-0 lg:gap-y-0 lg:px-8 xl:flex-row xl:items-stretch ">
                  <div className="w-full max-w-2xl p-10 xl:-mb-8 xl:w-96 xl:flex-none">
                    <div className="relative aspect-[2/1] h-full md:-mx-8 xl:mx-0 xl:aspect-auto">
                      <Image
                        src="/assets/images/profile.jpg"
                        width={200}
                        height={200}
                        alt={""}
                        className="absolute inset-0 h-60 w-60 rounded-full border-2 border-white bg-gray-800 object-cover shadow-2xl"
                      />
                    </div>
                  </div>
                  <div className="w-full max-w-2xl xl:max-w-none xl:flex-auto ">
                    <figure className="relative isolate p-0 sm:p-1 md:p-2 lg:p-3 xl:p-5">
                      <blockquote className="text-base font-semibold leading-8 text-black sm:text-2xl sm:leading-9 md:text-4xl lg:text-4xl xl:text-4xl">
                        <p>Tiaan Broodryk</p>
                      </blockquote>
                      <figcaption className="  text-xs sm:pt-1 sm:text-sm md:pt-4 md:text-base lg:pt-6 lg:text-lg xl:pt-8 xl:text-xl">
                        <div className="  text-black">
                          I am an software developer with a passion for creating
                          innovative and effective solutions to complex
                          problems. I thrive on working with cutting-edge
                          technologies and collaborating with other like-minded
                          individuals to explore and create new solutions. I am
                          highly motivated and strive to constantly learn and
                          improve my skills.
                        </div>
                        <div className=" text-gray-500">
                          intern software developer at netron
                        </div>
                      </figcaption>
                    </figure>
                  </div>
                </div>
              </div>
              <div className=" pt-20 text-center text-xl font-semibold sm:text-xl md:text-2xl lg:text-2xl xl:text-3xl"></div>
              <div className="bg-white py-24 sm:py-32">
                <div className="mx-auto max-w-7xl px-6 lg:px-8">
                  <div className="mx-auto max-w-2xl lg:mx-0">
                    <h2 className="text-3xl font-bold tracking-tight text-gray-900">
                      Contact me
                    </h2>
                    <p className="mt-6 text-lg leading-8 text-gray-600">
                      You can contact me on anny of the platforms below.
                    </p>
                  </div>
                  <div className="mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-8 text-base leading-7 sm:grid-cols-2 sm:gap-y-16 lg:mx-0 lg:max-w-none lg:grid-cols-4">
                    <div>
                      <h3 className="border-l border-indigo-600 pl-6 font-semibold text-gray-900">
                        Cell
                      </h3>
                      <address className="border-l border-gray-200 pl-6 pt-2 not-italic text-gray-600">
                        <p>078 410 4656</p>
                      </address>
                    </div>
                    <div>
                      <h3 className="border-l border-indigo-600 pl-6 font-semibold text-gray-900">
                        E-mail
                      </h3>
                      <address className="border-l border-gray-200 pl-6 pt-2 not-italic text-gray-600">
                        <p>tiaanbroodryk44@gmail.com</p>
                      </address>
                    </div>
                    <div>
                      <h3 className="border-l border-indigo-600 pl-6 font-semibold text-gray-900">
                        Linked In
                      </h3>
                      <address className="border-l border-gray-200 pl-6 pt-2 not-italic text-gray-600">
                        <p>in/tiaan-broodryk-1030b8273</p>
                      </address>
                    </div>
                    <div>
                      <h3 className="border-l border-indigo-600 pl-6 font-semibold text-gray-900">
                        Location
                      </h3>
                      <address className="border-l border-gray-200 pl-6 pt-2 not-italic text-gray-600">
                        <p>South Africa,Western-cape</p>
                        <p>Mossel bay</p>
                      </address>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="h-full min-h-screen bg-gray-100 sm:px-6 lg:px-8">
        <div className=" mx-auto max-w-6xl bg-white pt-20 text-center text-xl font-semibold sm:text-xl md:text-2xl lg:text-2xl xl:text-3xl">
          Projects i have been part of
          <div className="mt-16 grid grid-cols-1 gap-y-16 bg-white p-10 lg:grid-cols-2 lg:gap-x-8">
            <div className=" rounded-lg bg-slate-50 p-5 shadow-xl">
              <div className="aspect-h-2 aspect-w-3 w-full overflow-hidden rounded-lg">
                <Image
                  src="/assets/images/surreal.png"
                  width={800 * 2}
                  height={600 * 2}
                  alt={""}
                  className="  object-cover object-center"
                />
              </div>
              <h1>surrealreact.fly.dev/</h1>
              <p className="mt-8 text-base text-gray-500">
                Database aplication to navigate aroun in the database and add
                new data and tables.
              </p>
            </div>
            <div className=" rounded-lg bg-slate-50 p-5 shadow-xl">
              <div className="aspect-h-2 aspect-w-3 w-full overflow-hidden rounded-lg ">
                <Image
                  src="/assets/images/plasma.png"
                  width={800 * 2}
                  height={600 * 2}
                  alt={""}
                  className=" object-cover object-center"
                />
              </div>
              <h1>https://plasma-tech.vercel.app/</h1>
              <p className="mt-8 text-base">
                contact page aplication for a company in mosselbay to gent in
                touch with customers.
              </p>
            </div>
          </div>
        </div>
        <div className="mx-auto max-w-6xl bg-white ">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto max-w-2xl lg:mx-0">
              <h2 className="text-3xl font-bold tracking-tight text-gray-900">
                I Speasialize in these Technologies
              </h2>
            </div>
            <div className="mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-8 text-base leading-7 sm:grid-cols-2 sm:gap-y-16 lg:mx-0 lg:max-w-none lg:grid-cols-5">
              <div>
                <h3 className="border-l border-indigo-600 pl-6 font-semibold text-gray-900">
                  HTML
                </h3>
              </div>
              <div>
                <h3 className="border-l border-indigo-600 pl-6 font-semibold text-gray-900">
                  Typescript
                </h3>
              </div>
              <div>
                <h3 className="border-l border-indigo-600 pl-6 font-semibold text-gray-900">
                  React
                </h3>
              </div>
              <div>
                <h3 className="border-l border-indigo-600 pl-6 font-semibold text-gray-900">
                  Node
                </h3>
              </div>
              <div>
                <h3 className="border-l border-indigo-600 pl-6 font-semibold text-gray-900">
                  Rust
                </h3>
              </div>
            </div>
          </div>
          <div className="p-20"></div>
          <div className=" border-t border-white/10 bg-gray-800  pb-6 pt-10">
            <p className="text-xs leading-5 text-white">
              &copy; 2023 Tiaan Broodryk, Inc. All rights reserved.
            </p>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
